name             'nervios'
maintainer       'Charles Betz'
maintainer_email 'char@erp4it.com'
license          'MIT'
description      'cookbook for Nagios monitoring server'
long_description ''
version          '0.3.0'

depends     'apt'
depends     'apache2'
depends     'mysql'
depends     'php'
